export const initialFormData = {
    vehicleType: '',
    country: '',
    tripIntention: '',
    multipleDays: false,
    timeType: '',
    startDate: '',
    startTime: '',
    endDate: '',
    endTime: '',
    vehicleCategory: '',
    amenities: [],
    ownVehicleDetails: {
        category: '',
        transmission: '',
        brand: '',
        model: '',
        photo: null,
    },
    pickUp: '',
    dropOff: '',
    billingMethod: '',
    priceUnit: 0,
    currency: '',
    paymentMethod: '',
    negotiable: false,
};